import {Food} from './app/models/Food';

export const sample_foods:Food[] =[
    {
        id:'1',
        name:"pizza",
        price:250,
        tags:['FastFood', 'pizza'],
        favorite:false,
        stars:4.0,
        imageUrl: 'assets/food-1.jpg',
        origins: ['italy'],
        cookTime:'40-50',
    },
    {
        id:'2',
        name:"Burger",
        price:150,
        tags:['FastFood', 'Burger'],
        favorite:false,
        stars:4.0,
        imageUrl: 'assets/food-2.jpg',
        origins: ['italy'],
        cookTime:'20-30',
    },
    {
        id:'3',
        name:"Biryani",
        price:350,
        tags:['FastFood', 'Biryani'],
        favorite:true,
        stars:4.0,
        imageUrl: 'assets/food-3.jpg',
        origins: ['Haydarabad', 'India'],
        cookTime:'40-50',
    },
    {
        id:'4',
        name:"Handi Paneer",
        price:280,
        tags:['FastFood', 'Handi_Paneer'],
        favorite:false,
        stars:3.5,
        imageUrl: 'assets/food-4.jpg',
        origins: ['India', 'asia'],
        cookTime:'40-50',
    },
    {
        id:'5',
        name:"Kathi Roll",
        price:150,
        tags:['FastFood', 'Kathi_Roll'],
        favorite:false,
        stars:4.5,
        imageUrl: 'assets/food-5.jpg',
        origins: ['Germany', 'middle east' ],
        cookTime:'20-30',
    },
    {
        id:'6',
        name:"Bati chokha",
        price:350,
        tags:['Food', 'Bati_Chokha'],
        favorite:false,
        stars:5.0,
        imageUrl: 'assets/food-6.webp',
        origins: ['India', 'asia'],
        cookTime:'40-50',
    },
    {
        id:'7',
        name:"Paneer-tikka",
        price:250,
        tags:['Food', 'Paneer-tikka'],
        favorite:true,
        stars:5.0,
        imageUrl: 'assets/food-7.jpeg',
        origins: ['India'],
        cookTime:'40-50',
    },
    {
        id:'8',
        name:"Soya_Chaap",
        price:225,
        tags:['Food', 'Soya_Chaap'],
        favorite:false,
        stars:5.0,
        imageUrl: 'assets/food-8.jpeg',
        origins: ['India'],
        cookTime:'20-30',
    },
    {
        id:'9',
        name:"Baby-Corn",
        price:175,
        tags:['Food', 'Baby-Corn'],
        favorite:false,
        stars:5.0,
        imageUrl: 'assets/food-9.jpg',
        origins: ['Panjab', 'India'],
        cookTime:'15-20',
    },
    {
        id:'10',
        name:"pasta",
        price:150,
        tags:['Food', 'Pasta'],
        favorite:false,
        stars:5.0,
        imageUrl: 'assets/food-10.jpeg',
        origins: ['China', 'asia'],
        cookTime:'20-30',
    },
    {
        id:'11',
        name:"Tandoori-Momos",
        price:150,
        tags:['Food', 'Tandoori-Momos'],
        favorite:true,
        stars:5.0,
        imageUrl: 'assets/food-11.webp',
        origins: ['India'],
        cookTime:'40-50',
    },
    {
        id:'12',
        name:"Stuffed-Naan",
        price:75,
        tags:['Food', 'Stuffed-Naan'],
        favorite:false,
        stars:5.0,
        imageUrl: 'assets/food-12.jpg',
        origins: ['India', 'asia'],
        cookTime:'10-15',
    },
]